set -x

WORK_DIR=/opt/tiger/dwn-verl
MODEL=/mnt/bn/daiweinan-fuse/models/DeepSeek-R1-Distill-Qwen-1.5B
GPUS_PER_NODE=8
NNODES=8
ACTOR_MICRO_BS=$(( 8 * $NNODES ))
ROLLOUT_MICRO_BS=$(( 8 * $NNODES ))
ROLLOUT_TP=1
REF_MICRO_BS=$(( 8 * $NNODES ))
# EWMA_MICRO_BS=$(( 16 * $NNODES ))
CRITIC_MICRO_BS=$(( 8 * $NNODES ))
GRPO_GS=8

lr_warmup_steps=20

python3 -m verl.trainer.main_ppo \
    data.train_files=$WORK_DIR/run_deepscaler/train.parquet \
    data.val_files=$WORK_DIR/run_deepscaler/test_repeat3.parquet \
    data.train_batch_size=128 \
    data.val_batch_size=90 \
    data.max_prompt_length=3000 \
    data.max_response_length=8192 \
    actor_rollout_ref.model.path=$MODEL \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    +actor_rollout_ref.actor.optim.lr_warmup_steps=${lr_warmup_steps} \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size=$ACTOR_MICRO_BS \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.grad_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=$ROLLOUT_MICRO_BS \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.9 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=$REF_MICRO_BS \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    critic.optim.lr=1e-5 \
    +critic.optim.lr_warmup_steps=${lr_warmup_steps} \
    critic.model.path=$MODEL \
    critic.model.enable_gradient_checkpointing=True \
    critic.ppo_micro_batch_size=$CRITIC_MICRO_BS \
    critic.model.fsdp_config.param_offload=True \
    critic.model.fsdp_config.grad_offload=True \
    critic.model.fsdp_config.optimizer_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','tracking'] \
    trainer.project_name='dwn-verl' \
    trainer.experiment_name=64gpus/r1-distill-qwen-1.5b_hard60_grpo_bs128_minibs64_resp8k_gs8 \
    trainer.n_gpus_per_node=$GPUS_PER_NODE \
    trainer.nnodes=$NNODES \
    trainer.save_freq=-1 \
    trainer.test_freq=5 \
    trainer.total_epochs=30 \
    trainer.default_local_dir='/mnt/bn/daiweinan-fuse/models/${trainer.project_name}/${trainer.experiment_name}' \
    trainer.default_hdfs_dir='hdfs://haruna/home/byte_data_seed/lf_lq/user/daiweinan/models/${trainer.project_name}/${trainer.experiment_name}' \
    algorithm.use_grpo=True \
    actor_rollout_ref.actor.group_size=$GRPO_GS \
    algorithm.adv_estimator='norm_os' \
    actor_rollout_ref.actor.grpo_kl_coeff=0.001